# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=64)),
                ('brand_site', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=64)),
                ('products_price', models.IntegerField(default=0)),
                ('products_count', models.IntegerField(default=0)),
                ('products_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionStore.brand')),
            ],
        ),
        migrations.CreateModel(
            name='raiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting_stars', models.IntegerField(default=5)),
                ('raiting_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionStore.products')),
                ('raiting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='products_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionStore.type'),
        ),
    ]
